# Generated by Django 2.1.7 on 2019-03-13 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=5)),
                ('name', models.CharField(max_length=60)),
                ('track', models.CharField(choices=[('advanced', 'Advanced'), ('beginner', 'Beginner')], max_length=10)),
                ('required', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('excused', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('semester', 'date', 'student'),
            },
        ),
        migrations.CreateModel(
            name='Checkoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkoffs', to='main.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=5)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('sid', models.IntegerField()),
                ('track', models.CharField(choices=[('advanced', 'Advanced'), ('beginner', 'Beginner')], max_length=10)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='main.Semester')),
            ],
        ),
        migrations.AddField(
            model_name='facilitator',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilitators', to='main.Semester'),
        ),
        migrations.AddField(
            model_name='checkoff',
            name='facilitator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkoffs', to='main.Facilitator'),
        ),
        migrations.AddField(
            model_name='checkoff',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkoffs', to='main.Semester'),
        ),
        migrations.AddField(
            model_name='checkoff',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkoffs', to='main.Student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='main.Semester'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='main.Student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='main.Semester'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('sid', 'track', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='checkoff',
            unique_together={('student', 'assignment', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('semester', 'student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('semester', 'slug')},
        ),
    ]
